project_id = "mhznqgbszhzvyenlmtxb"
[functions.handle-lead-submission]
enabled = true
verify_jwt = true
import_map = "./functions/handle-lead-submission/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/handle-lead-submission/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/handle-lead-submission/*.html" ]
