// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upgswjsghyhnxxwuzxza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZ3N3anNnaHlobnh4d3V6eHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NDE2NTMsImV4cCI6MjA2MDQxNzY1M30.7CUGrhqxChCDsEPacFDcpb8NjZmRcsYW_GqHjWIGPmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);