// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhznqgbszhzvyenlmtxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oem5xZ2Jzemh6dnllbmxtdHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NjQ1ODIsImV4cCI6MjA2MjI0MDU4Mn0.4DMqEo4_xDaYR7QE3ZJLccgBWOgA1ddiuX_fdpvNc80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);